name: Build_and_run_tests_
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  BuildAndTest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore project
        run: dotnet restore "PowerCollections/PowerCollections.sln" 
      - name: Build project
        run: dotnet build "PowerCollections/PowerCollections.sln" --no-restore --configuration Release 
      - name: Test project
        run: dotnet test "PowerCollections.Tests/PowerCollections.Tests.sln" --no-build --verbosity normal --configuration Release 
